baseURL = "https://yiqiaowang.github.io"
languageCode = "en-us"
title = "Yi Qiao Wang"
theme = "hugo-theme-basic"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "about"
  url = "about/"
